export const tw = {
	education: '學歷',
	master: '碩士 - 台灣大學分子與細胞生物學研究所 (2016 - 2018)',
	bachelor: '學士 - 中興大學生物科技學士學位學程 (2012 - 2016)',
	intro_1: '2+年Vue.js開發經驗，熟悉相關套件(Vuex, Vue Router等)<br/>目前於KKday擔任前端工程師，執行點對點交通服務前、後台開發<br/>參與11+項線上大型專案開發，擁有跨團隊溝通及專案整合經驗。',
	intro_2: '過去任職於美商產品專員，具英日語實力，有跨國部門團隊溝通協商經驗，對工作細節高度敏銳及良好的專案流程進度掌控力。',
	page3_work_title: '工作 / 進修經歷',
	page3_lang_title: '語言能力',
	page3_skill_title: '應用技術',
	lang_desc_1: '英語 - 多益 940/990 (金色證書)',
	lang_desc_2: '英語 - 歐洲共同語言參考標準 C2 Proficient',
	lang_desc_3: '日語 - 日本語能力試驗 N2',
	career_title_kkday: 'KKday酷遊天國際旅行社',
	career_subtitle_kkday: '動態商品組 - 前端工程師',
	career_desc_kkday_1: '執行線上共 11+ 項交通服務前台頁面實作，內容包含API串接、共用元件設計，與UED、後端及其他團隊合作溝通',
	career_desc_kkday_2: '執行單元測試 (unit test)，讓整個專案測試覆蓋率達90%+，降低QC成本，提升代碼品質',
	career_desc_kkday_3: '將舊PC / Mobile平台專案整合為單一repo ，規劃共用Library及Design System元件開發',
	career_desc_kkday_4: '執行單元測試 (unit test)，讓整個專案測試覆蓋率達90%+，降低QC成本，提升代碼品質',
	career_title_tibame: '緯育TibaMe',
	career_subtitle_tibame: 'Web/APP前端設計工程師養成班學員',
	career_desc_tibame_1: '完成UI規劃設計、前台網頁開發(RWD)，成果榮獲最佳個人網站獎第1名',
	career_desc_tibame_2: '擔任組長帶領5人團隊以Vue框架進行團體專題開發，實作金物流API、後端資料庫串接及前台頁面動畫開發。',
	career_desc_tibame_3: '制定開發規則、專案分工、PC/Mobile mockup設計、協助組員解決專案技術上困難點。',
	career_title_polysciences: '美商欣科寶利股份公司',
	career_subtitle_polysciences: '產品技術專員',
	career_desc_polysciences_1: '0到1將主力GMP商品導入中國市場',
	career_desc_polysciences_2: '亞太區生物產品技術指導, 貿易金物流安排',
	career_desc_polysciences_3: '與美國總公司協商經銷策略',
	work_data_title_1: 'KKday - 點對點交通服務',
	work_data_desc_1: '交通服務PC / Mobile頁面實作。包含台灣高鐵、日本巴士、韓國機票、全球租車等11項交通服務。<br><br>透過串接供應商API，讓使用者能取得即時的資訊。並提供如選擇座位項目、升級車廂、加購商品等客製選項。<br><br>各服務皆包含售前及售後頁面。',
	work_data_title_2: 'Tibame前端工程師養成班 - 團體專題',
	work_data_desc_2: '實作和菓子購物網站，擔任組長帶領5人團隊進行開發，實作前台頁面動畫、金物流API及後端資料庫串接。',
	work_data_title_3: 'Tibame前端工程師養成班 - 個人專題',
	work_data_desc_3: '實作靜態網站，獨自完成UI規劃設計、各頁面開發(RWD)，成果榮獲最佳個人網站獎第1名。',
	link: '網站連結',
};

export const en = {
	education: 'Education',
	master: 'MS - NTU, Institute of Molecular and Cellular Biology (2016 - 2018)',
	bachelor: 'BS - NCHU, Biotechnology (2012 - 2016)',
	intro_1: '2+ years of Vue.js development experience, proficient in related libraries (Vuex, Vue Router, etc.)<br/>Currently working as a Frontend Engineer at KKday, involved in frontend and backend development for point-to-point transportation services<br/>Participated in the development of 11+ large-scale online projects, with experience in cross-team communication and project integration.',
	intro_2: 'Former Product Specialist at a US-based company, proficient in English and Japanese, with experience in cross-department team communication and negotiation. Strong attention to detail and excellent project progress control.',
	page3_work_title: 'Work/Training Experience',
	page3_lang_title: 'Language Ability',
	page3_skill_title: 'Web Skills',
	lang_desc_1: 'English - TOEIC : 940',
	lang_desc_2: 'English - CEFR : C2 Proficient',
	lang_desc_3: 'Japanese - JLPT : N2',
	career_title_kkday: 'KKday',
	career_subtitle_kkday: 'Frontend Engineer, Dynamic Product Team',
	career_desc_kkday_1: 'Participated 11+ online frontend pages for transportation services, including API integration and shared component design. Collaborated with UI/UX designers, backend developers, and other teams.',
	career_desc_kkday_2: 'Implemented unit tests to achieve test coverage of over 90%, reducing QC costs and improving code quality.',
	career_desc_kkday_3: 'Integrated old PC/Mobile platform projects into a single repository, planned and developed shared library and Design System components.',
	career_desc_kkday_4: 'Implemented unit tests to achieve test coverage of over 90%, reducing QC costs and improving code quality.',
	career_title_tibame: 'Wiedu TibaMe',
	career_subtitle_tibame: 'Web/APP Front End Web Development Courses',
	career_desc_tibame_1: 'Designed UI and developed frontend web pages (RWD), awarded 1st place for Best Personal Website.',
	career_desc_tibame_2: 'Led a team of 5 in group project development using Vue framework, implemented logistics APIs, backend database integration, and frontend animation development.',
	career_desc_tibame_3: 'Established development rules, project assignments, PC/Mobile mockup design, and assisted team members in overcoming technical challenges.',
	career_title_polysciences: 'Polysciences Asia Pacific, Inc.',
	career_subtitle_polysciences: 'Product specialist',
	career_desc_polysciences_1: 'Introduced GMP products into the Chinese market from scratch.',
	career_desc_polysciences_2: 'Technical guidance for biological products in the Asia-Pacific region, trade logistics arrangements.',
	career_desc_polysciences_3: 'Negotiated distribution strategies with the US headquarters.',
	work_data_title_1: 'KKday - Point-to-Point Transportation Services',
	work_data_desc_1: 'Implemented PC/Mobile pages for transportation services, including Taiwan High Speed Rail, Japan Bus, Korea Flight, and global car rental services.<br><br>Integrated with supplier APIs to provide real-time information and customizable options such as seat selection, cabin upgrades, and additional purchases.<br><br>Includes both pre-sales and post-sales pages.',
	work_data_title_2: 'Tibame Frontend Engineer Course - Group Project',
	work_data_desc_2: 'Developed a wagashi shopping website as a team leader with 5 members, implemented frontend animation, logistics APIs, and backend database integration.',
	work_data_title_3: 'Tibame Frontend Engineer Course - Individual Project',
	work_data_desc_3: 'Developed a static website individually, designed UI, developed all pages (RWD), awarded 1st place for Best Personal Website.',
	link: 'Website',
};