export const tw = {
	education: '學歷',
	master: '碩士 - 台灣大學分子與細胞生物學研究所 (2016 - 2018)',
	bachelor: '學士 - 中興大學生物科技學士學位學程 (2012 - 2016)',
	intro_1: '2+年Vue.js開發經驗，熟悉相關套件(Vuex, Vue Router等)\n目前於KKday擔任前端工程師，執行點對點交通服務前、後台開發\n參與11+項線上大型專案開發，擁有跨團隊溝通及專案整合經驗。',
	intro_2: '過去任職於美商產品專員，具英日語實力，有跨國部門團隊溝通協商經驗，對工作細節高度敏銳及良好的專案流程進度掌控力。',
	page3_work_title: '工作 / 進修經歷',
	page3_lang_title: '語言能力',
	page3_skill_title: '應用技術',
	lang_desc_1: '英語 - 多益 940/990 (金色證書)',
	lang_desc_2: '英語 - 歐洲共同語言參考標準 C2 Proficient',
	lang_desc_3: '日語 - 日本語能力試驗 N2',
	career_title_kkday: 'KKday酷遊天國際旅行社',
	career_subtitle_kkday: '動態商品組 - 前端工程師',
	career_desc_kkday_1: '執行線上共 11+ 項交通服務前台頁面實作，內容包含API串接、共用元件設計，與UED、後端及其他團隊合作溝通',
	career_desc_kkday_2: '執行單元測試 (unit test)，讓整個專案測試覆蓋率達90%+，降低QC成本，提升代碼品質',
	career_desc_kkday_3: '將舊PC / Mobile平台專案整合為單一repo ，規劃共用Library及Design System元件開發',
	career_desc_kkday_4: '執行單元測試 (unit test)，讓整個專案測試覆蓋率達90%+，降低QC成本，提升代碼品質',
	career_title_tibame: '緯育TibaMe',
	career_subtitle_tibame: 'Web/APP前端設計工程師養成班學員',
	career_desc_tibame_1: '完成UI規劃設計、前台網頁開發(RWD)，成果榮獲最佳個人網站獎第1名',
	career_desc_tibame_2: '擔任組長帶領5人團隊以Vue框架進行團體專題開發，實作金物流API、後端資料庫串接及前台頁面動畫開發。',
	career_desc_tibame_3: '制定開發規則、專案分工、PC/Mobile mockup設計、協助組員解決專案技術上困難點。',
	career_title_polysciences: '美商欣科寶利股份公司',
	career_subtitle_polysciences: '產品技術專員',
	career_desc_polysciences_1: '0到1將主力GMP商品導入中國市場',
	career_desc_polysciences_2: '亞太區生物產品技術指導, 貿易金物流安排',
	career_desc_polysciences_3: '與美國總公司協商經銷策略',
	link: '網站連結',
};

export const en = {
	education: 'Education',
	master: 'MS - NTU, Institute of Molecular and Cellular Biology',
	bachelor: 'BS - NCHU, Biotechnology',
	intro_1: 'Currently working as a Frontend Engineer at KKday, involved in the development of 7+ online projects. Job description includes processing frontend views of point-to-point transportation services, integrating functionalities, designing generic components, and unit tests writing.',
	intro_2: 'Previously worked as a Product Specialist in a US-based company, with experience in cross-functional and cross-border communication and negotiation. Highly sensitive to work details and possesses strong project management skills to control project progress.',
	page3_work_title: 'Work/Training Experience',
	page3_lang_title: 'Language Ability',
	page3_skill_title: 'Web Skills',
	lang_desc_1: 'English - TOEIC : 940',
	lang_desc_2: 'English - CEFR : C2 Proficient',
	lang_desc_3: 'Japanese - JLPT : N2',
	career_title_kkday: 'KKday',
	career_subtitle_kkday: 'New Business Team - Front-End Developer',
	career_desc_kkday_1: 'Participate in the development of 7+ online projects.',
	career_desc_kkday_2: 'Web vitals optimization, template design and development, and generic component design.',
	career_desc_kkday_3: 'System maintenance and operation, unit test writing.',
	career_title_tibame: 'Wiedu TibaMe',
	career_subtitle_tibame: 'Web/APP Front End Web Development Courses',
	career_desc_tibame_1: '1st Price of Personal project.',
	career_desc_tibame_2: 'Serve as the team leader and lead a 5 member team to carry out group project development, maintaining high integrity of the project.',
	career_desc_tibame_3: '制定開發規則、專案分工、PC/Mobile mockup設計、協助組員解決專案技術上困難點。',
	career_title_polysciences: 'Polysciences Asia Pacific, Inc.',
	career_subtitle_polysciences: 'Product specialist',
	career_desc_polysciences_1: "Introducing the company's flagship GMP-grade products into the Chinese market from zero to one.",
	career_desc_polysciences_2: 'Technical guidance on bioproducts, supplier trading, and financial logistics arrangements in the Asia-Pacific region.',
	career_desc_polysciences_3: 'Negotiating distribution strategies with the US headquarters.',
	link: 'Website',
};