export const tw = {
	master: '碩士 - 台灣大學分子與細胞生物學研究所',
	bachelor: '學士 - 中興大學生物科技學士學位學程',
	intro_1: '目前於KKday擔任新事業專案組前端工程師，參與7項以上全新且已上線之專案開發。工作內容包含負責點對點交通服務前端畫面處理、功能串接、通用元件設計、單元測試撰寫等。',
	intro_2: '過去任職於美商產品專員，有跨國不同部門團隊溝通協商經驗，對工作細節有高度敏銳，具備專案流程進度掌控力。',
	page3_work_title: '工作 / 進修經歷',
	page3_lang_title: '語言能力',
	page3_skill_title: '應用技術',
	lang_desc_1: '英語 - 多益 : 940',
	lang_desc_2: '英語 - 歐洲共同語文參考標準 : C2 Proficient',
	lang_desc_3: '日語 - 日本語能力試驗 : N2',
	career_title_kkday: 'KKday酷遊天國際旅行社',
	career_subtitle_kkday: '新事業專案組 - 前端工程師',
	career_desc_kkday_1: '點對點服務PC / M前端開發, 參與7項以上已上線專案開發',
	career_desc_kkday_2: '網頁效能優化, 設計模板開發, 通用元件設計',
	career_desc_kkday_3: '系統維運, 單元測試撰寫',
	career_title_tibame: '緯育TibaMe',
	career_subtitle_tibame: 'Web/APP前端設計工程師養成班學員',
	career_desc_tibame_1: '個人專體最佳個人網站第1名',
	career_desc_tibame_2: '擔任組長帶領5人小組進行團體專題開發, 保持專案高完整度',
	career_title_polysciences: '美商欣科寶利股份公司',
	career_subtitle_polysciences: '產品技術專員',
	career_desc_polysciences_1: '0到1將主力GMP商品導入中國市場',
	career_desc_polysciences_2: '亞太區生物產品技術指導, 貿易金物流安排',
	career_desc_polysciences_3: '與美國總公司協商經銷策略',
};

export const en = {
	master: 'MS - NTU, Institute of Molecular and Cellular Biology',
	bachelor: 'BS - NCHU, Biotechnology',
	intro_1: 'Currently working as a Frontend Engineer at KKday, involved in the development of 7+ launched projects. Job description includes processing frontend views of point-to-point transportation services, integrating functionalities, designing generic components, and unit tests writing.',
	intro_2: 'Previously worked as a Product Specialist in a US-based company, with experience in cross-functional and cross-border communication and negotiation. Highly sensitive to work details and possesses strong project management skills to control project progress.',
	page3_work_title: 'Work/Training Experience',
	page3_lang_title: 'Language Ability',
	page3_skill_title: 'Web Skills',
	lang_desc_1: 'English - TOEIC : 940',
	lang_desc_2: 'English - CEFR : C2 Proficient',
	lang_desc_3: 'Japanese - JLPT : N2',
	career_title_kkday: 'KKday',
	career_subtitle_kkday: 'New Business Team - Front-End Developer',
	career_desc_kkday_1: 'Participate in the development of 7+ online projects',
	career_desc_kkday_2: 'Web performance optimization, template design and development, and generic component design',
	career_desc_kkday_3: 'System maintenance and operation, unit test writing',
	career_title_tibame: 'Wiedu TibaMe',
	career_subtitle_tibame: 'Web/APP Front End Web Development Courses',
	career_desc_tibame_1: '1st Price of Personal project',
	career_desc_tibame_2: 'Serve as the team leader and lead a 5 member team to carry out group project development, maintaining high integrity of the project',
	career_title_polysciences: 'Polysciences Asia Pacific, Inc.',
	career_subtitle_polysciences: 'Product specialist',
	career_desc_polysciences_1: "Introducing the company's flagship GMP-grade products into the Chinese market from zero to one",
	career_desc_polysciences_2: 'Technical guidance on bioproducts, supplier trading, and financial logistics arrangements in the Asia-Pacific region.',
	career_desc_polysciences_3: 'Negotiating distribution strategies with the US headquarters',
};